baseURL = 'https://lyricsling.github.io/blog/'
defaultContentLanguage = "zh-cn"
languageCode = 'zh-cn'
title = '幻想涟漪'

theme = "gokarna"

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "Posts"

    url = "/posts/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = "<span data-feather='layout'>111111</span>"

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "文章"

    # Weights are used to determine the ordering
    weight = 1

 [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 2
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com"
    weight = 3
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"

[params]
	showPostsOnHomePage = "popular"

	accentColor = "#FF4D4D"

	footer = "Lyrics.ling"

 # Display "back to top" button on posts
  ShowBackToTopButton = true

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false

